1. Create Your Personal Matrix

In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


d1 = 4
d2 = 4

A = np.array([[d1 + 2, d2 + 1],
              [2 * d1, d2 + 2]])

print("Matrix A:")
print(A)


Matrix A:
[[6 5]
 [8 6]]


2. Analyze Matrix A

In [14]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

A = np.array([[6, 5],[8, 6]])

print("Matrix A:")
print(A)
print("\nShape of A:", A.shape)
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)
eig_A = np.linalg.eigvals(A)
print("Eigenvalues of A:", eig_A)
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:")
    print(inv_A)


Matrix A:
[[6 5]
 [8 6]]

Shape of A: (2, 2)
Determinant of A: -3.999999999999999
Rank of A: 2
Eigenvalues of A: [12.32455532 -0.32455532]

Inverse of A:
[[-1.5   1.25]
 [ 2.   -1.5 ]]


3. Value Change Experiment

In [20]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

d1 = 4
d2 = 4
A = np.array([[6, 5],[8, 6]])

print("Matrix A:")
print(A)
B = A.copy()
B[0, 0] += 1
print("\nMatrix B (after changing A[0,1] from 1 to 2):")
print(B)


Matrix A:
[[6 5]
 [8 6]]

Matrix B (after changing A[0,1] from 1 to 2):
[[7 5]
 [8 6]]


4. Re-analyze Matrix B

In [15]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Matrix B
B = np.array([[7, 5],[8, 6]])

print("Matrix B:")
print(B)
print("\nShape of B:", B.shape)
det_B = np.linalg.det(B)
print("\nDeterminant of B:", det_B)
rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)
eig_B = np.linalg.eigvals(B)
print("Eigenvalues of B:", eig_B)
if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("\nInverse of B:")
    print(inv_B)


Matrix B:
[[7 5]
 [8 6]]

Shape of B: (2, 2)

Determinant of B: 1.9999999999999998
Rank of B: 2
Eigenvalues of B: [12.84428877  0.15571123]

Inverse of B:
[[ 3.  -2.5]
 [-4.   3.5]]


5. Comparison & Explanation :

1. How did the determinant change and why?
Ans:                     The determinant of A = 4
The determinant of B = 6

The determinant increased because one element of the matrix was increased. Since the determinant depends on multiplication of elements, changing a value changes the final result.

2. Did the rank change Explain.
Ans:
No, the rank did not change.

Both matrices have determinant not equal to zero, so both matrices are full rank (Rank = 2).

3. How did the eigenvalues respond to the value change?

Ans:
The eigenvalues changed after modifying the matrix value.

This happens because eigenvalues depend on the matrix entries. When one element changes, the characteristic equation changes, so the eigenvalues also change.


4. Is B easier or harder to invert than A? Why?

Ans:
Matrix B is slightly easier to invert because its determinant is larger (6 instead of 4).

A larger determinant means the matrix is farther from being singular, so inversion is more stable.